server:
  port: 8190
  error:
    include-message: always
  forward-headers-strategy: framework
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: test1
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  hateoas:
    use-hal-as-default-json-media-type: false
application:
  max-allowed-books: 15
springdoc:
  swagger-ui:
    operationsSorter: method
    use-root-path: true
    path: /swagger-ui-custom.html
  api-docs:
    version: openapi_3_1
    path: /api-docs
