server:
  port: 8210
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: test1
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: reader-service
    max-allowed-books: 15
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    status-page-url-path: ${spring.cloud.client.hostname}